# Generated by Django 5.1.4 on 2024-12-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_alter_membership_options_alter_membership_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelTable(
            name='membership',
            table=None,
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
    ]
