# Generated by Django 5.1.4 on 2024-12-05 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_alter_membership_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default=datetime.datetime(2024, 12, 5, 10, 40, 43, 705783, tzinfo=datetime.timezone.utc), upload_to='book/images/'),
            preserve_default=False,
        ),
    ]
